// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgmWURSeWVCizstJC58zD0eayOxMic_8k',
    appId: '1:900968777377:web:41b8c8a6971facb0c492e0',
    messagingSenderId: '900968777377',
    projectId: 'langconnect-langtranslator',
    authDomain: 'langconnect-langtranslator.firebaseapp.com',
    storageBucket: 'langconnect-langtranslator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQfUhtfV-0U86HMTiG2342hdirheRFbs',
    appId: '1:900968777377:android:a7c27e575f2be824c492e0',
    messagingSenderId: '900968777377',
    projectId: 'langconnect-langtranslator',
    storageBucket: 'langconnect-langtranslator.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB71kwv0Kvp9qfK6M0e6Ddu0kAS5Hu_074',
    appId: '1:226605039149:web:9a3429be7d45e7d2de02a4',
    messagingSenderId: '226605039149',
    projectId: 'langconnect-translator',
    authDomain: 'langconnect-translator.firebaseapp.com',
    storageBucket: 'langconnect-translator.firebasestorage.app',
  );
}